JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true

REDIS_HOST=judge0-redis
REDIS_PASSWORD=codelearn-local-redis

POSTGRES_HOST=judge0-db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=codelearn-local-postgres
